# Generated by Django 2.0.5 on 2018-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vat_code', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('address01', models.CharField(max_length=100)),
                ('address02', models.CharField(max_length=100)),
                ('address03', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('is_mandatory_pass_reg', models.BooleanField(default='False')),
            ],
        ),
    ]
